version: '3'
services:
  container:
    build: ./container
    ports:
      - "3000:3000"
    command: npm run dev

  iu-registro-gastos-ingresos:
    build: ./iu-registro-gastos-ingresos
    ports:
      - "3001:3001"
    command: npm run dev

  iu-dashboard:
    build: ./iu-dashboard
    ports:
      - "3002:3002"
    command: npm run dev